
# STAGE 1: Build React App
FROM node:18-alpine as builder

WORKDIR /app

# Argumentos de Build (Injetados no CI)
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Copia dependências
COPY frontend/package*.json ./frontend/
COPY shared/ ./shared/

WORKDIR /app/frontend
RUN npm ci

# Copia código fonte
COPY frontend/ .

# Build
RUN npm run build

# STAGE 2: Nginx Server
FROM nginx:alpine

# Copia build final
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

# Copia configuração customizada do Nginx (SPA Support)
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
