package scanner

// Known vulnerable packages database
// In production, this would be fetched from NVD, OSV, or similar

func getKnownVulnerableNpmPackages() map[string]DependencyVulnerability {
	return map[string]DependencyVulnerability{
		"lodash": {
			Package:     "lodash",
			Severity:    "CRITICAL",
			Title:       "Prototype Pollution in lodash",
			Description: "Versions of lodash before 4.17.21 are vulnerable to Prototype Pollution",
			CVE:         "CVE-2021-23337",
			CWE:         "CWE-1321",
			CVSS:        7.2,
			FixVersion:  "4.17.21",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-23337",
			Ecosystem:   "npm",
		},
		"axios": {
			Package:     "axios",
			Severity:    "HIGH",
			Title:       "Server-Side Request Forgery in axios",
			Description: "Axios before 1.6.0 is vulnerable to SSRF",
			CVE:         "CVE-2023-45857",
			CWE:         "CWE-918",
			CVSS:        6.5,
			FixVersion:  "1.6.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-45857",
			Ecosystem:   "npm",
		},
		"express": {
			Package:     "express",
			Severity:    "MEDIUM",
			Title:       "Open Redirect in express",
			Description: "Express before 4.19.2 has an open redirect vulnerability",
			CVE:         "CVE-2024-29041",
			CWE:         "CWE-601",
			CVSS:        5.0,
			FixVersion:  "4.19.2",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2024-29041",
			Ecosystem:   "npm",
		},
		"jsonwebtoken": {
			Package:     "jsonwebtoken",
			Severity:    "HIGH",
			Title:       "JWT Algorithm Confusion in jsonwebtoken",
			Description: "jsonwebtoken before 9.0.0 allows algorithm confusion attacks",
			CVE:         "CVE-2022-23529",
			CWE:         "CWE-327",
			CVSS:        7.6,
			FixVersion:  "9.0.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-23529",
			Ecosystem:   "npm",
		},
		"minimist": {
			Package:     "minimist",
			Severity:    "CRITICAL",
			Title:       "Prototype Pollution in minimist",
			Description: "minimist before 1.2.6 is vulnerable to Prototype Pollution",
			CVE:         "CVE-2021-44906",
			CWE:         "CWE-1321",
			CVSS:        9.8,
			FixVersion:  "1.2.6",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-44906",
			Ecosystem:   "npm",
		},
		"node-fetch": {
			Package:     "node-fetch",
			Severity:    "HIGH",
			Title:       "Exposure of Sensitive Information in node-fetch",
			Description: "node-fetch before 2.6.7 exposes sensitive information",
			CVE:         "CVE-2022-0235",
			CWE:         "CWE-200",
			CVSS:        6.1,
			FixVersion:  "2.6.7",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-0235",
			Ecosystem:   "npm",
		},
		"moment": {
			Package:     "moment",
			Severity:    "HIGH",
			Title:       "ReDoS in moment",
			Description: "moment before 2.29.4 is vulnerable to ReDoS",
			CVE:         "CVE-2022-31129",
			CWE:         "CWE-1333",
			CVSS:        7.5,
			FixVersion:  "2.29.4",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-31129",
			Ecosystem:   "npm",
		},
		"qs": {
			Package:     "qs",
			Severity:    "HIGH",
			Title:       "Prototype Pollution in qs",
			Description: "qs before 6.10.3 is vulnerable to Prototype Pollution",
			CVE:         "CVE-2022-24999",
			CWE:         "CWE-1321",
			CVSS:        7.5,
			FixVersion:  "6.10.3",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-24999",
			Ecosystem:   "npm",
		},
		"shell-quote": {
			Package:     "shell-quote",
			Severity:    "CRITICAL",
			Title:       "Command Injection in shell-quote",
			Description: "shell-quote before 1.7.3 allows command injection",
			CVE:         "CVE-2021-42740",
			CWE:         "CWE-78",
			CVSS:        9.8,
			FixVersion:  "1.7.3",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-42740",
			Ecosystem:   "npm",
		},
		"tar": {
			Package:     "tar",
			Severity:    "HIGH",
			Title:       "Arbitrary File Creation in tar",
			Description: "tar before 6.1.11 allows arbitrary file creation",
			CVE:         "CVE-2021-37701",
			CWE:         "CWE-22",
			CVSS:        8.6,
			FixVersion:  "6.1.11",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-37701",
			Ecosystem:   "npm",
		},
		"underscore": {
			Package:     "underscore",
			Severity:    "CRITICAL",
			Title:       "Arbitrary Code Execution in underscore",
			Description: "underscore before 1.13.6 allows arbitrary code execution",
			CVE:         "CVE-2021-23358",
			CWE:         "CWE-94",
			CVSS:        7.2,
			FixVersion:  "1.13.6",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-23358",
			Ecosystem:   "npm",
		},
		"glob-parent": {
			Package:     "glob-parent",
			Severity:    "HIGH",
			Title:       "ReDoS in glob-parent",
			Description: "glob-parent before 5.1.2 is vulnerable to ReDoS",
			CVE:         "CVE-2020-28469",
			CWE:         "CWE-1333",
			CVSS:        7.5,
			FixVersion:  "5.1.2",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2020-28469",
			Ecosystem:   "npm",
		},
		"path-parse": {
			Package:     "path-parse",
			Severity:    "MEDIUM",
			Title:       "ReDoS in path-parse",
			Description: "path-parse before 1.0.7 is vulnerable to ReDoS",
			CVE:         "CVE-2021-23343",
			CWE:         "CWE-1333",
			CVSS:        5.3,
			FixVersion:  "1.0.7",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2021-23343",
			Ecosystem:   "npm",
		},
		"serialize-javascript": {
			Package:     "serialize-javascript",
			Severity:    "HIGH",
			Title:       "Arbitrary Code Execution in serialize-javascript",
			Description: "serialize-javascript before 3.1.0 allows arbitrary code execution",
			CVE:         "CVE-2020-7660",
			CWE:         "CWE-502",
			CVSS:        8.1,
			FixVersion:  "3.1.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2020-7660",
			Ecosystem:   "npm",
		},
		"y18n": {
			Package:     "y18n",
			Severity:    "HIGH",
			Title:       "Prototype Pollution in y18n",
			Description: "y18n before 5.0.5 is vulnerable to Prototype Pollution",
			CVE:         "CVE-2020-7774",
			CWE:         "CWE-1321",
			CVSS:        7.3,
			FixVersion:  "5.0.5",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2020-7774",
			Ecosystem:   "npm",
		},
	}
}

func getKnownVulnerableGoPackages() map[string]DependencyVulnerability {
	return map[string]DependencyVulnerability{
		"github.com/dgrijalva/jwt-go": {
			Package:     "github.com/dgrijalva/jwt-go",
			Severity:    "HIGH",
			Title:       "JWT Validation Bypass",
			Description: "jwt-go allows attackers to bypass intended access restrictions",
			CVE:         "CVE-2020-26160",
			CWE:         "CWE-287",
			CVSS:        7.5,
			FixVersion:  "4.0.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2020-26160",
			Ecosystem:   "go",
		},
		"github.com/gin-gonic/gin": {
			Package:     "github.com/gin-gonic/gin",
			Severity:    "MEDIUM",
			Title:       "Improper Input Validation in Gin",
			Description: "Gin before 1.9.0 has improper input validation",
			CVE:         "CVE-2023-26125",
			CWE:         "CWE-20",
			CVSS:        5.3,
			FixVersion:  "1.9.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-26125",
			Ecosystem:   "go",
		},
		"golang.org/x/crypto": {
			Package:     "golang.org/x/crypto",
			Severity:    "HIGH",
			Title:       "Panic in SSH Server",
			Description: "golang.org/x/crypto before 0.17.0 has a panic vulnerability",
			CVE:         "CVE-2023-48795",
			CWE:         "CWE-354",
			CVSS:        5.9,
			FixVersion:  "0.17.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-48795",
			Ecosystem:   "go",
		},
		"golang.org/x/net": {
			Package:     "golang.org/x/net",
			Severity:    "HIGH",
			Title:       "HTTP/2 Rapid Reset Attack",
			Description: "golang.org/x/net before 0.17.0 is vulnerable to HTTP/2 rapid reset",
			CVE:         "CVE-2023-44487",
			CWE:         "CWE-400",
			CVSS:        7.5,
			FixVersion:  "0.17.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-44487",
			Ecosystem:   "go",
		},
		"github.com/go-yaml/yaml": {
			Package:     "github.com/go-yaml/yaml",
			Severity:    "HIGH",
			Title:       "Denial of Service in go-yaml",
			Description: "go-yaml before 2.2.8 is vulnerable to DoS via crafted YAML",
			CVE:         "CVE-2022-28948",
			CWE:         "CWE-400",
			CVSS:        7.5,
			FixVersion:  "2.2.8",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-28948",
			Ecosystem:   "go",
		},
	}
}

func getKnownVulnerablePipPackages() map[string]DependencyVulnerability {
	return map[string]DependencyVulnerability{
		"django": {
			Package:     "django",
			Severity:    "HIGH",
			Title:       "SQL Injection in Django",
			Description: "Django before 4.2.8 has SQL injection vulnerability",
			CVE:         "CVE-2023-46695",
			CWE:         "CWE-89",
			CVSS:        7.5,
			FixVersion:  "4.2.8",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-46695",
			Ecosystem:   "pip",
		},
		"flask": {
			Package:     "flask",
			Severity:    "MEDIUM",
			Title:       "Information Disclosure in Flask",
			Description: "Flask before 2.3.2 may disclose sensitive information",
			CVE:         "CVE-2023-30861",
			CWE:         "CWE-200",
			CVSS:        5.3,
			FixVersion:  "2.3.2",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-30861",
			Ecosystem:   "pip",
		},
		"requests": {
			Package:     "requests",
			Severity:    "MEDIUM",
			Title:       "Information Disclosure in Requests",
			Description: "Requests before 2.31.0 leaks Proxy-Authorization headers",
			CVE:         "CVE-2023-32681",
			CWE:         "CWE-200",
			CVSS:        6.1,
			FixVersion:  "2.31.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-32681",
			Ecosystem:   "pip",
		},
		"pillow": {
			Package:     "pillow",
			Severity:    "HIGH",
			Title:       "Buffer Overflow in Pillow",
			Description: "Pillow before 10.0.1 has buffer overflow vulnerability",
			CVE:         "CVE-2023-44271",
			CWE:         "CWE-120",
			CVSS:        7.5,
			FixVersion:  "10.0.1",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-44271",
			Ecosystem:   "pip",
		},
		"pyyaml": {
			Package:     "pyyaml",
			Severity:    "CRITICAL",
			Title:       "Arbitrary Code Execution in PyYAML",
			Description: "PyYAML before 5.4 allows arbitrary code execution",
			CVE:         "CVE-2020-14343",
			CWE:         "CWE-94",
			CVSS:        9.8,
			FixVersion:  "5.4",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
			Ecosystem:   "pip",
		},
		"jinja2": {
			Package:     "jinja2",
			Severity:    "MEDIUM",
			Title:       "XSS in Jinja2",
			Description: "Jinja2 before 3.1.3 has XSS vulnerability",
			CVE:         "CVE-2024-22195",
			CWE:         "CWE-79",
			CVSS:        5.4,
			FixVersion:  "3.1.3",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2024-22195",
			Ecosystem:   "pip",
		},
		"cryptography": {
			Package:     "cryptography",
			Severity:    "HIGH",
			Title:       "NULL Pointer Dereference in cryptography",
			Description: "cryptography before 41.0.6 has NULL pointer dereference",
			CVE:         "CVE-2023-49083",
			CWE:         "CWE-476",
			CVSS:        7.5,
			FixVersion:  "41.0.6",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-49083",
			Ecosystem:   "pip",
		},
		"urllib3": {
			Package:     "urllib3",
			Severity:    "MEDIUM",
			Title:       "Cookie Leakage in urllib3",
			Description: "urllib3 before 2.0.7 leaks cookies across redirects",
			CVE:         "CVE-2023-45803",
			CWE:         "CWE-200",
			CVSS:        4.2,
			FixVersion:  "2.0.7",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-45803",
			Ecosystem:   "pip",
		},
	}
}

func getKnownVulnerableComposerPackages() map[string]DependencyVulnerability {
	return map[string]DependencyVulnerability{
		"symfony/http-kernel": {
			Package:     "symfony/http-kernel",
			Severity:    "HIGH",
			Title:       "Remote Code Execution in Symfony",
			Description: "Symfony HttpKernel before 6.3.8 allows RCE",
			CVE:         "CVE-2023-46734",
			CWE:         "CWE-94",
			CVSS:        8.8,
			FixVersion:  "6.3.8",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-46734",
			Ecosystem:   "composer",
		},
		"laravel/framework": {
			Package:     "laravel/framework",
			Severity:    "HIGH",
			Title:       "SQL Injection in Laravel",
			Description: "Laravel before 10.35.0 has SQL injection vulnerability",
			CVE:         "CVE-2023-52428",
			CWE:         "CWE-89",
			CVSS:        7.5,
			FixVersion:  "10.35.0",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2023-52428",
			Ecosystem:   "composer",
		},
		"guzzlehttp/guzzle": {
			Package:     "guzzlehttp/guzzle",
			Severity:    "HIGH",
			Title:       "SSRF in Guzzle",
			Description: "Guzzle before 7.4.5 is vulnerable to SSRF",
			CVE:         "CVE-2022-31090",
			CWE:         "CWE-918",
			CVSS:        7.7,
			FixVersion:  "7.4.5",
			URL:         "https://nvd.nist.gov/vuln/detail/CVE-2022-31090",
			Ecosystem:   "composer",
		},
	}
}
