package autofix

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// GitHubPRCreator creates pull requests with auto-fixes
type GitHubPRCreator struct {
	token string
	owner string
	repo  string
}

// NewGitHubPRCreator creates a new PR creator
func NewGitHubPRCreator(token, owner, repo string) *GitHubPRCreator {
	return &GitHubPRCreator{
		token: token,
		owner: owner,
		repo:  repo,
	}
}

// CreatePRWithFix creates a PR with the auto-fix applied
func (g *GitHubPRCreator) CreatePRWithFix(fix *AutoFix, scanID uint, vulnCount int) (string, error) {
	// 1. Get default branch
	defaultBranch, err := g.getDefaultBranch()
	if err != nil {
		return "", fmt.Errorf("failed to get default branch: %v", err)
	}
	
	// 2. Get latest commit SHA
	latestSHA, err := g.getLatestCommitSHA(defaultBranch)
	if err != nil {
		return "", fmt.Errorf("failed to get latest commit: %v", err)
	}
	
	// 3. Create new branch
	branchName := fmt.Sprintf("aegis-fix-%s-%d", strings.ToLower(strings.ReplaceAll(fix.VulnType, " ", "-")), time.Now().Unix())
	if err := g.createBranch(branchName, latestSHA); err != nil {
		return "", fmt.Errorf("failed to create branch: %v", err)
	}
	
	// 4. Get current file content (if exists)
	currentContent, currentSHA, _ := g.getFileContent(fix.FilePath, branchName)
	
	// 5. Apply patch
	newContent := g.applyPatch(currentContent, fix.Patch)
	
	// 6. Commit changes
	commitMessage := fmt.Sprintf("🔒 Security: Fix %s\n\nAuto-generated by AegisScan (Scan #%d)\n\n%s", fix.VulnType, scanID, fix.Description)
	if err := g.commitFile(branchName, fix.FilePath, newContent, commitMessage, currentSHA); err != nil {
		return "", fmt.Errorf("failed to commit file: %v", err)
	}
	
	// 7. Create PR
	prTitle := fmt.Sprintf("🔒 [AegisScan] Fix %s", fix.VulnType)
	prBody := g.buildPRBody(fix, scanID, vulnCount)
	prURL, err := g.createPR(branchName, defaultBranch, prTitle, prBody)
	if err != nil {
		return "", fmt.Errorf("failed to create PR: %v", err)
	}
	
	return prURL, nil
}

func (g *GitHubPRCreator) getDefaultBranch() (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s", g.owner, g.repo)
	
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("GitHub API error: %s", string(body))
	}
	
	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	
	return result["default_branch"].(string), nil
}

func (g *GitHubPRCreator) getLatestCommitSHA(branch string) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/git/refs/heads/%s", g.owner, g.repo, branch)
	
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("GitHub API error: %s", string(body))
	}
	
	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	
	object := result["object"].(map[string]interface{})
	return object["sha"].(string), nil
}

func (g *GitHubPRCreator) createBranch(branchName, sha string) error {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/git/refs", g.owner, g.repo)
	
	payload := map[string]interface{}{
		"ref": "refs/heads/" + branchName,
		"sha": sha,
	}
	body, _ := json.Marshal(payload)
	
	req, _ := http.NewRequest("POST", url, bytes.NewBuffer(body))
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 201 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API error: %s", string(respBody))
	}
	
	return nil
}

func (g *GitHubPRCreator) getFileContent(filePath, branch string) (string, string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/contents/%s?ref=%s", g.owner, g.repo, filePath, branch)
	
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode == 404 {
		// File doesn't exist yet
		return "", "", nil
	}
	
	if resp.StatusCode != 200 {
		body, _ := io.ReadAll(resp.Body)
		return "", "", fmt.Errorf("GitHub API error: %s", string(body))
	}
	
	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	
	content := result["content"].(string)
	sha := result["sha"].(string)
	
	// Decode base64 content
	// Note: GitHub returns base64 encoded content
	// For simplicity, we'll return as-is and handle in applyPatch
	
	return content, sha, nil
}

func (g *GitHubPRCreator) applyPatch(currentContent, patch string) string {
	// Simple implementation: append patch to end of file
	// In production, you'd want smarter merging
	
	if currentContent == "" {
		return patch
	}
	
	return currentContent + "\n\n" + patch
}

func (g *GitHubPRCreator) commitFile(branch, filePath, content, message, sha string) error {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/contents/%s", g.owner, g.repo, filePath)
	
	payload := map[string]interface{}{
		"message": message,
		"content": content, // Should be base64 encoded
		"branch":  branch,
	}
	
	if sha != "" {
		payload["sha"] = sha
	}
	
	body, _ := json.Marshal(payload)
	
	req, _ := http.NewRequest("PUT", url, bytes.NewBuffer(body))
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 200 && resp.StatusCode != 201 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API error: %s", string(respBody))
	}
	
	return nil
}

func (g *GitHubPRCreator) createPR(headBranch, baseBranch, title, body string) (string, error) {
	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", g.owner, g.repo)
	
	payload := map[string]interface{}{
		"title": title,
		"body":  body,
		"head":  headBranch,
		"base":  baseBranch,
	}
	reqBody, _ := json.Marshal(payload)
	
	req, _ := http.NewRequest("POST", url, bytes.NewBuffer(reqBody))
	req.Header.Set("Authorization", "token "+g.token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")
	
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != 201 {
		respBody, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("GitHub API error: %s", string(respBody))
	}
	
	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)
	
	return result["html_url"].(string), nil
}

func (g *GitHubPRCreator) buildPRBody(fix *AutoFix, scanID uint, vulnCount int) string {
	return fmt.Sprintf(`## 🔒 Security Fix: %s

This PR was automatically generated by **AegisScan** to fix a security vulnerability.

### 📊 Scan Information
- **Scan ID**: #%d
- **Total Vulnerabilities**: %d
- **Vulnerability Type**: %s
- **Confidence**: %s

### 🔧 What This PR Does
%s

### 📝 Changes Made
**File**: %s

**Patch**:
` + "```" + `%s
%s
` + "```" + `

### ✅ Testing
Run the following command to verify the fix:
` + "```bash" + `
%s
` + "```" + `

### 🎯 Next Steps
1. Review the changes
2. Run tests to ensure nothing breaks
3. Test the security header: ` + "`curl -I https://your-site.com`" + `
4. Merge if everything looks good

### 📚 References
- [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/)
- [AegisScan Documentation](https://github.com/your-org/aegis-scan)

---
🤖 **Auto-generated by AegisScan v5.0**  
💡 Questions? Check the [documentation](https://github.com/your-org/aegis-scan/docs) or open an issue.
`, 
		fix.VulnType,
		scanID,
		vulnCount,
		fix.VulnType,
		fix.Confidence,
		fix.Description,
		fix.FilePath,
		fix.Language,
		fix.Patch,
		fix.TestCommand,
	)
}
